name: Heroku Deploy

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    
    env:
      PROJECT_NAME: "Artigo-Medium-Heroku"
      SOLUTION_NAME: "Artigo-Medium-Heroku"
      HEROKU_APP_NAME: "artigo-medium-heroku"
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.100-preview.5.21302.13
      
      - name: Buildando a aplicação
        run: |
          cd ${{ env.SOLUTION_NAME }}/${{ env.PROJECT_NAME }}/
          dotnet clean
          dotnet build
      
      - name: Deployando a aplicação para o Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          cd ${{ env.SOLUTION_NAME }}/${{ env.PROJECT_NAME }}/
          
          dotnet clean
          dotnet build
          dotnet publish -c Release -r linux-x64 -p:PublishReadyToRun=true -o ../publish 
          
          cd ../publish
          
          dockerfileContent="FROM mcr.microsoft.com/dotnet/aspnet:6.0 \n"
          dockerfileContent+="WORKDIR /app \n"
          dockerfileContent+="COPY . . \n"
          dockerfileContent+="EXPOSE 80 443 \n"
          dockerfileContent+="CMD ASPNETCORE_URLS=http://*:$PORT ./${{ env.PROJECT_NAME }} \n"
          
          echo -e $dockerfileContent > Dockerfile
          
          docker build -t ${{ env.HEROKU_APP_NAME }} .
          
          heroku container:login
          heroku container:push web -a ${{ env.HEROKU_APP_NAME }}
          heroku container:release web -a ${{ env.HEROKU_APP_NAME }}
          
          echo "Deploy concluído com sucesso! =)"
